// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9qB_iZNUNyN-A_Xoi8dFDIqpc7k2MEHs',
    appId: '1:206776602718:web:6870d8f6dbdcb90eefe4cf',
    messagingSenderId: '206776602718',
    projectId: 'fbasedbtuto',
    authDomain: 'fbasedbtuto.firebaseapp.com',
    storageBucket: 'fbasedbtuto.appspot.com',
    measurementId: 'G-P0CRH7WG6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB2h7PncWLArRryG_ezCMEua-WmcgkWRU',
    appId: '1:206776602718:android:6e38091c714968d9efe4cf',
    messagingSenderId: '206776602718',
    projectId: 'fbasedbtuto',
    storageBucket: 'fbasedbtuto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB55ndfE2zrdt5i3MZOggfkPOICnurXI0g',
    appId: '1:206776602718:ios:bdfe080b1888ba86efe4cf',
    messagingSenderId: '206776602718',
    projectId: 'fbasedbtuto',
    storageBucket: 'fbasedbtuto.appspot.com',
    iosClientId: '206776602718-4bk0o3gq8de8edjc2n04q1kcas62m8u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbasedbtuto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB55ndfE2zrdt5i3MZOggfkPOICnurXI0g',
    appId: '1:206776602718:ios:bdfe080b1888ba86efe4cf',
    messagingSenderId: '206776602718',
    projectId: 'fbasedbtuto',
    storageBucket: 'fbasedbtuto.appspot.com',
    iosClientId: '206776602718-4bk0o3gq8de8edjc2n04q1kcas62m8u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbasedbtuto',
  );
}
